apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-sentinel.fullname" . }}-redis-config
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
data:
  redis.conf: |
    {{- .Values.redis.configuration | nindent 4 }}
    {{- if .Values.redis.auth.enabled }}
    requirepass {{ .Values.redis.auth.password }}
    {{- end }}
    {{- if and .Values.redis.auth.enabled .Values.redis.auth.acl.enabled }}
    aclfile /opt/redis/acl.conf
    {{- end }}
  {{- if and .Values.redis.auth.enabled .Values.redis.auth.acl.enabled }}
  acl.conf: |
    {{- range .Values.redis.auth.acl.users }}
    user {{ .username }} on >{{ .password }} {{ .permissions }}
    {{- end }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-sentinel.fullname" . }}-sentinel-config
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
data:
  sentinel.conf: |
    # Basic sentinel configuration
    port 26379
    
    # Monitor the master - using service name that resolves to cluster IP
    sentinel resolve-hostnames yes
    sentinel monitor mymaster redis-redis-sentinel-redis-master.redis.svc.cluster.local 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel parallel-syncs mymaster 1
    sentinel failover-timeout mymaster 10000
    
    {{- if .Values.redis.auth.enabled }}
    sentinel auth-pass mymaster {{ .Values.redis.auth.password }}
    {{- end }}
    
    # Additional configuration from values
    {{- if .Values.sentinel.configuration }}
    {{- .Values.sentinel.configuration | nindent 4 }}
    {{- end }}