{{- if .Values.redis.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-sentinel.fullname" . }}-auth
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- if .Values.redis.auth.acl.enabled }}
  {{- range .Values.redis.auth.acl.users }}
  {{ .username }}-password: {{ .password | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}